### ISSUE TITLE
OpenSSL support in 1.8.x and 2.x

### ISSUE THREAD

**Issue by greenrobot** [benmcollins/libjwt#211]
Coming from v1.17.2, we wanted to update to a pre-3.x version, but it seems that 0.18.x requires OpenSSL 3.0 to compile. This prevents us from running on older OS releases.

```
../../jwt-src/libjwt/jwt-openssl.c:163:7: error: call to undeclared function 'EVP_PKEY_get_group_name'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        if (!EVP_PKEY_get_group_name(pkey, groupNameBuffer, sizeof(groupNameBuffer), &groupNameBufferLen))
```

EVP_PKEY_get_group_name got added in OpenSSL 3.0: https://docs.openssl.org/3.0/man3/EVP_PKEY_get_group_name/#history

I can see that this was ifdef-ed in version 2.x, but with e.g. 2.1.1 we see this compilation failure:

```
cmake-build-debug/_deps/jwt-src/libjwt/jwt.c:40:42: error: use of undeclared identifier 'jwt_gnutls_ops'
static struct jwt_crypto_ops *jwt_ops = &jwt_gnutls_ops;
```

There's a `#ifdef HAVE_OPENSSL` around that, but it seems to be not set (we are using CMake).

So, we have not found a solution to build libjwt yet.

**Comment by greenrobot** [comment]
A workaround that works with 2.1.1 is `target_compile_definitions(jwt PRIVATE HAVE_OPENSSL)`, e.g.:

```
include(FetchContent)
FetchContent_Declare(
        ${PROJECT_NAME}
        GIT_REPOSITORY "https://github.com/benmcollins/libjwt.git"
        GIT_TAG "v${LIBJWT_VERSION}"
)
FetchContent_MakeAvailable(${PROJECT_NAME})
target_compile_definitions(jwt PRIVATE HAVE_OPENSSL)  # libjwt does not set this via CMake?
```

**Comment by benmcollins** [comment]
Prior to v3, CMake was not a fully supported build environment. It was mainly added to help with WIN32 compilation. Autotools was the supported method for all other targets before LibJWT v3.

As far as OpenSSL 1.1 support in LibJWT v3, I am more than happy for someone to provide code for a `libjwt/openssl-compat/` if they would like to help. The complexity of the code to have OpenSLL 1.1 compatibility `ifdef`d with the OpenSSL 3 was too much for one person (me) to deal with, especially with the addition of JWK support.

**Comment by benmcollins** [comment]
In addition, for LibJWT v2, patches for OpenSSL 1.1 or anything else beyond bugs and security fixes, will not likely be accepted, but I'm open to consider any PRs, and appreciate that migrating to LibJWT v3 is not going to happen quickly or easily for a lot of users.

I do invite any help with that. Just remember, this project is something I do on my own time, and could certainly use a bit more community assistance around it.

**Comment by lgrosz** [comment]
I don’t want to create any false expectations, but I may explore adding
OpenSSL 1.1 support for LibJWT v3. My work currently relies on a Yocto
system based on Sumo, which, due to other less malleable dependencies, does
not support OpenSSL 3. However, we are nearing completion of our migration
to Yocto Kirkstone, which would eliminate this requirement.

That said, I understand the challenges of maintaining an open-source
project and appreciate the effort involved. While I can’t make any
commitments, I am genuinely interested in contributing where time permits.

**Comment by ChristianSchulte** [comment]
This has been discussed recently on the OpenBSD [@ports](https://marc.info/?l=openbsd-ports&m=173996660807553&w=2) list when I tried to create a libjwt1.18 port. I added the suggested fix to the port. The patch file is contained in the libjwt.tar.gz archive attached to the mail (www/libjwt/patches/patch-libjwt_jwt-openssl_c). It would be great if we could get a v1.18.4  tag with this patch applied to make it work with OpenBSD libressl currently in base. Thank you.

**Comment by ChristianSchulte** [comment]
Works for me. Thanks a lot.

**Comment by ChristianSchulte** [comment]
Just for the record. Companies providing REST APIs do not provide keys in JKS format. They just provide private keys in PEM format. Converting those to JKS is a PITA. Would be cool, if you could provide some kind of tool converting those PEM encoded keys to JKS, so that an upgrade to libjwt2 or even libjwt3 is not that painful.

**Comment by lgrosz** [comment]
> Just for the record. Companies providing REST APIs do not provide keys in JKS format. They just provide private keys in PEM format. Converting those to JKS is a PITA. Would be cool, if you could provide some kind of tool converting those PEM encoded keys to JKS, so that an upgrade to libjwt2 or even libjwt3 is not that painful.
>

I believe that exists in this repo.. a binary built called `key2jwk`.
